data:
  # There is wikipedia dataset as well but it can be used directly from datasets library
  news:
    path: /Users/vinitmehta/Desktop/IIITH/Sem7/IRE/Assignments/HomeworkIRE/data/news
    unzip: true # Download the data and unzip it
  wikipedia:
    path: /Users/vinitmehta/Desktop/IIITH/Sem7/IRE/Assignments/HomeworkIRE/data/wikipedia

top_k_threshold: 50 # Top K words to be plotted in frequency distribution plots
output_folder_path: /Users/vinitmehta/Desktop/IIITH/Sem7/IRE/Assignments/HomeworkIRE/output
